#!/bin/sh
# Copyright (C) 2018-2024 NIC.br
# Released under the public domain or GPLv2+ at your option

# Spoofer V2 needs either CAP_NET_RAW or SUID root
[ -x /usr/bin/sspooferc ] && chmod u+s /usr/bin/sspooferc || true

# stable seed for pseudo-random numbers
seed=$(printf %u "0x$(get_mac_address.sh | tail -c 5)") || seed=

# Update crontabs:
# cleanup history for upgrades:
#   previous: simetbox_register_ma.sh
#   current : simetbox_refresh_cron.sh simet_geolocation.sh

{ crontab -l 2>/dev/null | sed -e '/simetbox_refresh_cron/ d' -e '/simetbox_register_ma/ d' -e '/simet_geolocation.sh/ d' ;
  awk -- "BEGIN { srand($seed);
		  print int(60*rand()) \" \" int(24*rand()) \" * * * simetbox_refresh_cron.sh\" ;
		  print int(60*rand()) \" 1,5,9,13,17,21 * * * simet_geolocation.sh\"
		}" ; } | crontab -

# remove simet_ma.ixbr_ping.* uci entries, measurement removed
uci -q batch <<-EOFUCI >/dev/null
	delete simet_ma.ixbr_ping
	commit simet_ma
EOFUCI
:
