#!/bin/sh
# Copyright (C) 2018-2020 NIC.br
# Released under the public domain or GPLv2+ at your option
#
# cleanup history for upgrades:
#  previous: simetbox_register_ma.sh
#  current : simetbox_refresh_cron.sh simet_geolocation.sh

seed=$(printf %u "0x$(get_mac_address.sh | tail -c 5)") || seed=

( crontab -l 2>/dev/null | sed -e '/simetbox_refresh_cron/ d' -e '/simetbox_register_ma/ d' -e '/simet_geolocation.sh/ d' ;
  awk -- "BEGIN { srand($seed);
		  print int(60*rand()) \" \" int(24*rand()) \" * * * simetbox_refresh_cron.sh\" ;
		  print int(60*rand()) \" 1,5,9,13,17,21 * * * simet_geolocation.sh\"
		}" ) | crontab -
:
