#!/bin/sh
# Copyright (c) 2019 NIC.br
# Released under the public domain or GPLv2+ at your option

set -e
set -o pipefail

command -v simet_create_vlabel.sh >/dev/null 2>&1 && {
	VLABEL=$(simet_create_vlabel.sh) || exit 1
	if [ -n "$VLABEL" ] ; then
		logger -s -t simet-ma daemon.notice "MA virtual label: $VLABEL"
	else
		logger -s -t simet-ma daemon.notice "MA virtual label disabled/unavailable"
	fi
}
:
