#!/bin/sh /etc/rc.common

# SIMET2-MA - SIMET2 Measurement Agent services
# Copyright (c) 2018 NIC.br
# Distributed under the GPLv2+

START=99
STOP=10
USE_PROCD=1

simet_config() {
	RC=0
	. /usr/lib/simet/simet_lib_config.sh || RC=$?
	if [ $RC -ne 0 ] || [ -z "$AGENT_ID_FILE" ] || [ -z "$AGENT_TOKEN_FILE" ] || \
		[ -z "$GEOLOC_CACHE" ] || [ -z "$SIMET_INETUP_SERVER" ] ; then
		echo "$0: required configuration missing, aborting..." >&2
		exit 1
	fi

	BOXID=$(get_mac_address.sh 2>/dev/null | tr A-F a-f | tr -d ': -') || true
	BOOTID=$(cat /proc/sys/kernel/random/boot_id) || true
}

boot() {
	simet_config

	GEO_DIR=$(dirname "${GEOLOC_CACHE}")
	[ -n "$GEO_DIR" ] && mkdir -m 0750 -p "$GEO_DIR" && chgrp nicbr-simet "$GEO_DIR"
	# warning: try to keep RAM load down for 32MiB devices!
	( simet_register_ma.sh <&- 2>&- >&- && {
		simet_geolocation.sh <&- 2>&- >&- || true
		simetbox_lmap-fetch-schedule.sh <&- 2>&- &
	} ) <&- 2>&- >&- &
	start "$@"
}

start_service() {
	simet_config

	procd_open_instance simet-inetuptime
	procd_set_param file "$AGENT_ID_FILE" "$AGENT_TOKEN_FILE" /usr/lib/simet/simet-ma.conf /etc/simet/simet-ma.conf /usr/lib/simet/conf.d/*
	procd_set_param user nicbr-simet
	procd_set_param pidfile /var/run/simet-inetupc.pid
	procd_set_param respawn 180 5 10
	procd_set_param stderr 1
	procd_set_param reload_signal HUP
	procd_set_param command /usr/bin/inetupc -M "${LMAP_TASK_NAME_PREFIX}inetconn-state"
	[ -n "$AGENT_TOKEN_FILE" ] && procd_append_param command -j "$AGENT_TOKEN_FILE"
	[ -n "$AGENT_ID_FILE" ] && procd_append_param command -d "$AGENT_ID_FILE"
	[ -n "$BOOTID" ] && procd_append_param command -b "$BOOTID"
	[ -n "$BOXID" ] && procd_append_param command -m "$BOXID"
	procd_append_param command "$SIMET_INETUP_SERVER"
	procd_close_instance
}

# openwrt-CC doesn't handle procd_send_signal or reload_signal, but
# just in case we manage to backport either...
reload_service() {
	procd_send_signal simet-ma '*' HUP || killall -HUP inetupc
}
