#!/bin/sh

. /lib/functions/network.sh

# LAC-BCOP-1
# FR-15: Enable BCP-38 filtering by default on standard configuration

lacbcop_bcp38() {
	network_find_wan WANIF true || WANIF=wan
	[ "$( uci get network.$WANIF 2>/dev/null )" = "interface" ] || exit 0
	WANPIF=$(uci get network.$WANIF.ifname) || exit 0
	[ -n "$WANPIF" ] || exit 0
	[ "$( uci get bcp38.@bcp38[0] 2>/dev/null )" = "bcp38" ] || exit 0

	case "$( uci get bcp38.@bcp38[0].enabled 2>/dev/null )" in
		1|true|on|yes|enabled)
			exit 0
	esac

	uci -q batch <<-EOT >/dev/null
		set bcp38.@bcp38[0].interface=$WANPIF
		set bcp38.@bcp38[0].enabled=1
		set bcp38.@bcp38[0].detect_upstream=1
		commit bcp38
	EOT
}

lacbcop_bcp38 || true

exit 0

